bluesky-social/atproto-website

content/guides/overview.md
=> Minor: fix typos

content/guides/applications.md
=> Fix typo in Applications Model #app.bsky.feed.like

content/guides/lexicon.md
Hi amazing developers,
I fixed typo pointed out in #7.
=> fix: fixed typo related to #7

components/footer.js
Changes hard coded value into JS function
=> Footer year should not be static

content/lexicons/app-bsky-feed.md
This PR adds the `getPosts` Lexicon. 👍
=> Add getPosts Lexicon

content/lexicons/app-bsky-actor.md, content/lexicons/app-bsky-embed.md, content/lexicons/app-bsky-feed.md, content/lexicons/app-bsky-graph.md
Here's another Lexicon update @pfrazee. 👍
=> Add Lexicons for labeling embeds and Blocks

content/guides/applications.md
Sessions are created with `com.atproto.server.createSession` method.
Closes #44
=> Fix signing in example

README.md, content/specs/atp.md
- Adds auth documentation and details for app passwords
- Tidy up README
=> Add auth & app password docs and clean up README

components/footer.js, components/header.js, components/hero.js, components/sidebar.js, content/community/groups.md, content/community/projects.md, content/community/quick-start.md, content/docs.yml, lib/content.js, pages/community.js, pages/community/[id].js, pages/guides/[id].js, pages/lexicons/[id].js, pages/specs/[id].js
- Adds community tab: quick start guide, community projects, community groups 
- Renames "Developer" section to "Documentation"
=> Add community tab

content/community/groups.md
- fixes 404 on a link to join a community dev group
=> Fix: group link

content/community/projects.md
We're on the Play Store now :)
https://play.google.com/store/apps/details?id=dev.mozzius.graysky
=> Add Graysky to the list of android apps

content/community/projects.md, content/specs/atp.md
now that the web app is available directly at [bsky.app](https://bsky.app/) 🎉
=> Remove staging prefix on web app

content/community/projects.md
Add https://github.com/uakihir0/bsky4j (Java clinent)
=> Add bsky4j to projects.md

components/meta.js, next.config.js
This PR does the following changes:
1. 061ee8058f85ee0b9b1def023ca8fb613af0db2e Adds the missing `lang=en` attribute to html tag.
~~f1f68f3e0f255260aa65c5ca511fe39eb3a238dc Defines explicit sizes of image. (Doesn't do any changes to img aspect ratio)~~
3. b67e1b57656747e1aa3940fde0f5574aec801f98 Adds meta description tag
=> Improves website accessibility

next.config.js
=> redir atproto.com/faq -> atproto.com/guides/faq

components/meta.js, next.config.js
reverts changes introduced in #49 to isolate build issue
=> Revert config changes for build

content/lexicons/com-atproto-identity.md
- updates lexicon to match changes in https://github.com/bluesky-social/atproto/pull/1048
=> Update com.atproto.identity.resolveHandle lexicon

content/community/projects.md
I updated the description of atp tooling to be more transparent on it's functionality.
=> Update atp tooling listing in projects.md

content/community/projects.md
ATprotoのWebクライアントです。
追加していただけたらうれしいです。
=> add redocean

components/footer.js, components/header.js, components/sidebar.js, content/blog/block-implementation.md, content/community/quick-start.md, content/docs.yml, lib/content.js, pages/blog.js, pages/blog/[id].js
- adds tab for developer blog 
- adds first dev blog post for public blocks
=> Add tab for developer blog

content/community/projects.md
bot-account : https://bsky.app/profile/did:plc:4hqjfn7m6n5hno3doamuhgef
=> add community/projects bots

content/specs/at-uri-scheme.md
Another "just documenting current usage" sort of spec.
Tagging in Paul on this one in case he didn't get to review the notion doc earlier.
=> specs/at-uri-scheme: re-write AT URI spec

content/specs/did.md, content/specs/handle.md
Combined, a bunch of additional specs on how to work with identity in atproto.
=> specs: handle resolution and did document details

content/specs/xrpc.md
Based on comments from Slack. I haven't implemented this myself, so not super confident, but this is also just a temporary scheme.
Also indicated that the admin token scheme is probably temporary.
=> specs/xrpc: inter-service JWT auth

content/blog/federation-developer-sandbox.md, content/docs.yml
- Adds blog post for guidelines & instructions for federation developer sandbox
=> Add federation dev sandbox blog post

content/community/projects.md
Adds [Langit](https://github.com/intrnl/langit) to community projects page
=> docs: add langit to community projects

content/community/projects.md
Added my feedgen, which is basically an expanded version of the official one.
Not sure if there is formatting etiquette (i.e. two links, link ordering, etc.)?
=> Added Bossett's feedgen to Custom Feeds

content/community/projects.md
Add FishyFlip to AT Protocol Implementations
=> Add FishyFlip

content/blog/federation-developer-sandbox.md
the rendering engine was converting `:plcs` to a newline for some reason.
=> minor bug fix for federation blog post

content/community/projects.md
Added the [Rijden de Treinen](https://bsky.app/profile/rijdendetreinen.nl) bot to the bot section of projects.
=> Add rijdendetreinen bot

content/community/projects.md
Added Bluesky Social Feeds, a tool to search and build custom feeds without code or regex
=> Added Bluesky Social Feeds to Projects: Custom Feeds

components/header.js, package-lock.json, package.json, yarn.lock
- Adds [search](https://docsearch.algolia.com/)
=> Add docs search

content/blog/create-post.md, content/guides/data-repos.md
A couple mistakes I noticed in the docs
=> fix link and wording

components/footer.js, content/community/projects.md, content/community/quick-start.md
=> update Bluesky PBLLC to PBC (Public Benefit Corporation)

content/community/projects.md
Added my community project submission under the "Bridges" section
=> Added my community project submission

components/cta.js, components/footer.js, components/header.js, components/hero.js, content/community/groups.md, content/community/quick-start.md, content/docs.yml, pages/index.js
- add links to github discussions (original motivation)
- promote sandbox instead of waitlist
- deep link in to overview and specs
- slightly less Bluesky PBC oriented (though still prominently mentioned/linked)
=> update links; tweak homepage hero and call to action

content/specs/handle.md
closes: https://github.com/bluesky-social/atproto-website/issues/205
=> handle: add .example, .alt to list of reserved TLDs

components/footer.js, components/mailing-list.js, content/blog/rate-limits-pds-v3.md, pages/blog/[id].js, styles/globals.css
- Adds a place for people to subscribe to the developer mailing list, both at the end of every dev blog post & at the footer of the entire site
=> Add dev mailing list submission form

pages/index.js
Noticed a typo on the home page so here is a tiny PR to fix it.
=> Typo fix on the home page

content/community/projects.md
Added to list of community projects: 
Fedica's Bluesky scheduling/thread composer support
=> Added Fedica's scheduling support for Bluesky

content/community/projects.md
I developed a tool that allowed Twitter/X to generate images of circles of friends with whom we interact the most. I decided to bring this application to Bluesky and offer it to community projects.
The app is available at https://skycle.app
Thanks for accept my PR. 😊
=> Added Skycle.app in community projects

content/community/projects.md
=> Use app store links for graysky

content/blog/repo-export.md, content/docs.yml
pairs with cookbook PR: https://github.com/bluesky-social/cookbook/pull/3
=> blog: Working with AT Protocol Repository Exports

content/guides/overview.md
- updates broken lexicon links
- my code editor got rid of some trailing whitespace i'm so sorry
=> update broken lexicon links

content/specs/xrpc.md
I think this may have been a typo?
=> Ambiguity in XRPC pagination section

content/community/projects.md
Added an entry to the iOS section adding a reference to the app "Skeets"
=> Add an entry to the iOS section adding a reference to the app "Skeets"

content/community/projects.md
I'm working on a client with PWA support.
https://subium.com
https://bsky.app/profile/subium.com
---
Thanks for the Bluesky and a such opened platform 👍
=> Add Subium to Web clients

content/community/projects.md
https://github.com/sugyan/atrium
=> Add ATrium to Rust implementations

content/community/projects.md
I developed AT Protocol Implementation in Swift.
repository: https://github.com/nnabeyang/swift-atproto
=> Added swift-atproto in community projects

content/community/projects.md
Launched this week in early access! 
- [Available here](https://useouranos.app)
- [Learn more](https://useouranos.app/about)
- [Link to the repository](https://github.com/pdelfan/ouranos)
=> Add Ouranos to Community Projects

content/community/projects.md
Skywalker is an Android client for Bluesky
=> Add Skywalker app

components/sidebar.js
Changed `overflow-y-scroll` to `overflow-y-auto`
=> Only show scrollbar in sidebar if necessary

LICENSE.txt
Small PR to update copyright year in the LICENSE file.
=> Update copyright year in LICENSE.txt

content/specs/xrpc.md
Adds details about how to use service-specific signing keys in inter-service auth JWTs.
I also walked back the "this is temporary" language a bit. We might expand to other token types in the future, but this JWT mechanism probably isn't going away for a while.
=> specs/xrpc: service token with identifier in iss

content/specs/label.md
=> specs/label: typo fixes

src/app/[locale]/articles/atproto-for-distsys-engineers/en.mdx, src/app/[locale]/articles/atproto-for-distsys-engineers/pt.mdx, src/app/[locale]/guides/applications/en.mdx, src/app/[locale]/guides/applications/pt.mdx, src/components/mdx.tsx
Large images were not constrained to the container before.
=> Put max-width on mdx images

src/components/Guides.tsx
Link is currently broken on atproto.com
=> Fixed self-hosting link in guides

src/app/[locale]/guides/applications/en.mdx, src/app/[locale]/guides/applications/ja.mdx, src/app/[locale]/guides/applications/pt.mdx
just a super small change, renaming kysley typos to kysely!
=> fix: rename kysley to kysely

src/app/[locale]/specs/atp/page.mdx, src/app/[locale]/specs/blob/page.mdx, src/components/Navigation.tsx
=> blobs spec

src/app/[locale]/specs/atp/page.mdx
=> specs: update overview with now-specified stuff :tada: 

src/app/[locale]/specs/oauth/page.mdx
Something I ran into while trying to implement OAuth login myself.
=> IME scopes_supported is an array

src/app/[locale]/guides/glossary/en.mdx, src/app/[locale]/guides/identity/en.mdx, src/app/[locale]/guides/lexicon/en.mdx, src/app/[locale]/guides/overview/en.mdx, src/app/[locale]/guides/self-hosting/en.mdx, src/components/Libraries.tsx, src/components/Navigation.tsx
These should get replaced soon, or at least deeply edited. But I did a quick pass to remove any glaring confusions or factual inaccuracies about the current protocol.
=> partial corrections to guides

src/app/[locale]/guides/overview/en.mdx
Very minor grammatical error correction.
=> Add missing "of" in protocol overview

src/styles/tailwind.css
=> change punctuation color for code to be more visible

LICENSE.txt, src/components/Libraries.tsx
=> use legally registered name for company

src/app/[locale]/specs/repository/en.mdx, src/app/[locale]/specs/sync/en.mdx
Don't want folks coming in to the specs and being unaware of this work-in-progress.
=> add sync v1.1 proposal links
