bluesky-social/atproto-website

content/guides/identity.md, content/guides/lexicon.md, content/guides/overview.md, content/specs/atp.md, content/specs/did-plc.md, content/specs/lexicon.md, content/specs/xrpc.md
Spotted a small number of typos while working through the docs and figured I'd fix 'em while I was looking.
=> Fix a few doc typos

content/specs/did-plc.md
change "... contains a reference the the immediately preceding ..." to "... contains a reference to the immediately preceding ..."
=> fix typo on specs/did-plc page

content/guides/overview.md, content/specs/atp.md, next.config.js
`/lexicons/com-atproto` is a broken link ([see here](https://atproto.com/lexicons/com-atproto)), so changed references to `/lexicons/com-atproto-identity`.
Your next.config.js should handle the redirect, but I suspect that because `/lexicons/com-atproto-account` is _also_ not a valid path that this isn't working.
Included a docs update for the active/valid `/lexicons/app-bsky-actor` link as well.
=> Fixing documentation links for atproto-com

content/guides/identity.md, content/specs/atp.md
`com.atproto.handle.resolve` was renamed to `com.atproto.identity.resolveHandle` in commit 0f32224d99eda717ceba1ffbc02585e15811bada. Fix remaining references to `com.atproto.handle`.
=> com.atproto.handle.resolve renamed to com.atproto.identity.resolveHandle

content/community/projects.md
Add the BlueSky CLI from Wes Bos to the community projects page, a typescript CLI app to view the feed and posts.
- [blue-sky-cli](https://github.com/wesbos/blue-sky-cli)
=> Add blue-sky-cli (Typescript)

content/community/projects.md
...since I extracted the ATP PDS code out of Bridgy Fed into its own library.
thanks for open sourcing the site so we can all file PRs!
=> community page: remove Bridgy Fed, add arroba

content/community/projects.md
SkyDeck is a Bluesky Social client that lets you follow multiple feeds at once.
=> Added SkyDeck to community projects

content/community/projects.md
Adding link to socialweb/atproto-lexicon library, a Lexicon schema parser for PHP applications/tools/libraries: https://github.com/socialweb-php/atproto-lexicon
Originally submitted as a PR and merged here: https://github.com/bluesky-social/atproto-ecosystem/pull/48
=> Add link to socialweb/atproto-lexicon library

components/cta.js, components/footer.js, components/header.js, components/hero.js, lib/content.js, pages/community.js, pages/community/[id].js, pages/docs.js, pages/guides/[id].js, pages/lexicons/[id].js, pages/specs/[id].js
Small improvements to page structure (html landmarks) and CSS in order to make the site more usable to folks who are using screen readers or keyboard navigation:
- apply [keyboard focus rings](https://build.washingtonpost.com/resources/accessibility/keyboard-accessibility#Focus%20rings) on clickable elements that didn't have them i.e. "Community" link and guides on docs page
- for improved contrast/visibility, use yellow-gold focus outline color in cases where a link is over a blue background
- reorganize [semantic html headers & page landmarks](https://build.washingtonpost.com/resources/accessibility/semantic-html#Heading%20order%20and%20page%20landmarks) to improve navigation experience for screen reader users
- minor tweaks to alt text and aria-labels to make meanings more clear for …
=> fix: improve keyboard and screen reader accessibility

content/community/projects.md
Add Linux Kernel Releases. A bot that posts new Linux kernel versions from www.kernel.org.
It edits https://atproto.com/community/projects#bots 
Bot link: https://bsky.app/profile/linuxkreleases.adilson.net.br
=> Add Linux Kernel Releases Bot to project.md

content/docs.yml, content/specs/handle.md
This hasn't been formally reviewed by somebody else, but the handle identifier is pretty stable and this matches what the typescript `atproto` implementation does very closely. This document could probably also include docs on handle *resolution* process in addition to the handle *identifier*.
Mostly tossing this PR up to see how much work it is to go from an internal spec doc to basic public web doc. Answer, with notion markdown export, is basically trivial to get this far. Will want to do additional copy-editing and formatting, but there is also the option to just ship some of these fast to get the details out there, and polish presentation later.
=> specs: add 'handle' spec doc

content/specs/nsid.md
There were some small changes here that were reviewed and merged upstream in atproto (typescript) by @dholms first: https://github.com/bluesky-social/atproto/pull/1085
Notably, not allowing digits in the "method name" part, and being more permissive about the "domain authority" part.
=> specs/nsid: re-write NSID spec

content/specs/nsid.md
Tiny change, will bypass review and self-merge.
=> specs/nsid: fix markdown copy/paste error with URL

content/docs.yml, content/specs/record-key.md
These specs were totally missing, so happy to get them in!
There are some references to "TID" elsewhere that should get updated to point to this doc. For the specs ones, i'll be doing a pass over all the specs so will presumably hit those in the near future.
=> specs: Record Key identifier (including TID)

content/specs/record-key.md
Pretty trivial, will probably bypass review.
=> specs/record-key: fix base42 typo

content/docs.yml, content/specs/event-stream.md
I think @dholms may already have given this a read-over. Almost no changes vs the notion version from last week.
The one major change I could see making here is using "Subscription" instead of "Event Stream".
=> specs/event-stream: initial specification

content/docs.yml, content/specs/data-model.md
Didn't change much since the internal notion version. Decided to move string formatting details over to the Lexicon doc, as those are more about validation against a specific Lexicon. Did add an explicit note about "nullable" and "false-y" values.
cc: @dholms @devinivy
=> specs/data-model: initial specification

content/docs.yml, content/specs/lexicon.md
Put @devinivy on this one, but also cc: @dholms
**Questions for Reviewers (not part of spec doc)**
Can we say that a Lexicon *must* have at least one definition (`defs`)?
Can a `union` have an empty `refs` list, or must there always be at least one ref? What if `closed=true`? Is an empty list the same as `undefined`?
Can any types be indicated by a `ref`? What about in a `union`? How is a union disambiguate non-object types? Eg, multiple strings with different format. Nullable union and a `null` option.
Should subscription schemas *always* be a union of refs (with names)?
Why do we have `com.atproto.admin.defs#videoDetails`?
`const` and `default` are only defined for a handful of primitive types. Is this intentional?
=> specs/lexicon: re-write

content/specs/atp.md
This is kind of an arbitrary place to stick this, but I feel like tech folks are often confused about whether atproto uses IPFS. This tries to clarify that it is not currently used, while also leaving the door open.
Totally open to communicating this some other way, different wording, etc, just opening as a PR for a concrete discussion.
=> specs: mention that IPFS is not used

content/specs/cryptography.md
This has come up a couple times, think I finally found the right jargon to describe the issue.
I'm not actually super confident in the requirement here, but the typescript reference implementation *does* reject low-S signatures (apparently), so seems best to require them broadly for consistency? If we decide to go ahead with this, somebody (can be me) should add tests for all of our implementations (typescript, golang, did-plc) to ensure we are consistent.
cc: @whyrusleeping in case you have an opinion
=> cryptography: note about ECDSA sigs and low-S requirement

content/community/projects.md, content/guides/data-repos.md, content/specs/lexicon.md
These are pretty small/simple, may self-merge.
For the bridgy-fed link, not sure why that was linked from an NSID name; the targeted file is a 404. I think snarfed refactored code between projects.
=> fix broken links and typos

content/community/projects.md
Taken from the [archived ecosystem repository](https://github.com/bluesky-social/atproto-ecosystem/blob/7cd25805420c3736d17df1e802d49aae8d167982/app-passwords.md), helps to clarify why app passwords are beneficial when using third-party clients, especially ones you don't trust.
=> Expand on app passwords usage

content/guides/identity.md
Fix links to Handles and DIDs specs in Identity guide. The text shows markdown links syntax instead the rendered links. This pull request fixes them with HTML `<a>` tags.
=> Fix links to specs in Identity guide

content/specs/lexicon.md
Updates link in lexicon spec to properly point to the NSID spec rather than the handle spec.
=> fix: use correct link to NSID spec

content/community/projects.md
I added a link to repository of a project I made to let people share their domain for custom handles. The working app is at https://handles.domi.zip/
=> Adding open-handles project to the list

content/community/projects.md
Added an entry for ScoreMyWordle, which is a bot that now runs across Bluesky, Mastodon, and Twitter.
=> Update projects to include ScoreMyWordle bot

content/community/projects.md
I've moved my 2 Ruby projects from the general "ATProto implementations" category to "firehose" and "custom feeds", and added one more project which is an equivalent of `feed-generator` repo in Ruby.
=> community projects: move some projects to subcategories

content/specs/handle.md
Short addition to have something in here when this feature goes live (soon now).
Could expand on the semantics a bit more.
cc: @pfrazee who discussed this recently in https://github.com/bluesky-social/atproto/issues/1362
=> specs/handle: document handle.invalid special value

content/specs/lexicon.md
Finally getting around to this. Tagging Devin on this one as he did the typescript implementation (back in late June).
closes: https://github.com/bluesky-social/atproto-website/issues/128
=> specs/lexicon: document 'language' string format

content/specs/nsid.md
Copied from https://github.com/bluesky-social/atproto/blob/73f64009a22b3428a21a6d7807aee89d629fd0a4/packages/nsid/src/index.ts#L100
This now matches `cn.8.lex.stuff`, which the old regex didn't.
Not sure why the code used `[a-zA-Z]([a-zA-Z]{0,61}[a-zA-Z])?` instead of `[a-zA-Z]{1,63}`, but I don't think it's worth changing in the `atproto` repo given limited review bandwidth, and I'd rather this regex was exactly the same as their, than have it be slightly more concise here.
=> Fix NSID regex.

content/guides/identity.md
Something seems borked with rendering markdown:
After:
I don't know why.
=> Add backticks to fix rendering

content/community/projects.md
Hi! I've noticed that the list of ATProto implementation projects got a bit long and chaotic, so I propose grouping the project into sections by language (with languages ordered alphabetically).
=> Community: group implementations by language

components/sidebar.js
_UX finetuning_
* Previously, devices with limited viewport height will clip the content inside `sidebar.js`. Users can now scroll through overflow on sidebar vertical nav. Previously, they had to scroll to the bottom of the main prose content for remaining items to show up
Before - As the number of `<Link />` tags grow within these docs, scrolling to a target `<Link />` through main prose content can get cumbersome. In this example, the target `<Link />` is highlighted in red.
https://user-images.githubusercontent.com/56938909/234152533-1ef62784-543f-4888-82ca-91a653b271ee.mp4
After - sidebar vertical nav is now scrollable on its own. overflow scrolling behavior only appears when viewport clips content, so `position: sticky` behavior still persists …
=> update sidebar.js - now scrollable when sidebar content overflows

content/specs/cryptography.md, content/specs/did.md
DO NOT MERGE YET!
This is prep for changes to DID Document formatting, key encoding, and use of `Multikey` type in `verifiedMethod` objects. Also moves key encoding info in to the crypto page (out of DID), except for the special-case legacy format (which will get deprecated eventually).
cc: @dholms
=> specs: update DID document and crypto key encoding

content/community/projects.md
This adds SkySweeper to the tools section, as recommended at https://bsky.app/profile/emily.bsky.team/post/3kaujhnwht62d.
=> Add SkySweeper to tools section

content/specs/lexicon.md
Some clarifications and extra language around datetime.
Left some ambiguity about "earliest supported date" until we have consensus on that, but i'm tempted to stay that datetimes before UNIX epoch are just not allowed, as out-of-scope for what we intend this field to be used for. Eg, we might want to convert `createdAt` to a UNIX timestamps as an internal thing in various databases, and that won't work with older dates. Maybe that is too unexpected/conservative though.
=> specs: clarifications with datetime format

content/community/projects.md
I adjusted the link because the original fragment identifier no longer points to a valid location. It now directs readers to the current App Password documentation.
This has been tested locally.
=> fix app password link

content/specs/lexicon.md
Per recent discussion!
I wasn't sure if we want to make this a "must" for references inside lexicon schema docs themselves (as opposed to in data `$type` fields) so I used contortions to avoid being explicit about that.
=> specs/lexicon: clarify non-use of #main fragment in `$type`

content/community/projects.md
Adds a stable R package (currently on [CRAN](https://cran.r-project.org/web/packages/bskyr/index.html)) to the project listing.
=> Add bskyr to community projects

content/community/projects.md
Hey team,
we're happy to announce that we launched our social media management integration today. With Swat.io, you can plan and publish your bluesky content and also mange your community - just within one tool. 
Would be nice to get added to the list 😻
=> Add Swat.io to list of Community Projects

components/footer.js, content/guides/faq.md, content/guides/overview.md
This PR updates three links that currently point to `blueskyweb.xyz` to instead point to the equivalent pages on `bsky.social`.
=> Update blueskyweb.xyz links to equivalent pages on bsky.social

content/specs/xrpc.md
Closes: https://github.com/bluesky-social/atproto-website/issues/231
=> specs/xrpc: fix admin basic auth example

content/specs/repository.md
Resolve compatibility issues with "nullable and optional" fields in this core data structure with golang.
Background here: https://github.com/bluesky-social/indigo/issues/327
Basically signatures fail to validate in golang if the field is not included but `null`.
It would have been possible to just remove this field from the spec, or have it be optional (but not nullable) and those would have worked fine with golang, but the boat has basically sailed (tons of existing data in this format). So we'll stick with requiring the field exist, but be nullable.
=> specs: v3 commit prev as nullable but non-optional

content/specs/repository.md
This must have been a typo/mistake when writing these up last year. My bad!
thanks to @mary-ext and @str4d for pointing this out.
closes: #297
=> specs: fix missing/swapped 't' and 'v' fields in MST nodes

content/specs/xrpc.md
Spec is pretty simple so far. I hedged things a bit with a disclaimer, as I won't be surprised if we end up adding:
- `/.well-known/` pre-flight check
- ability to not forward on service token (or reduce it's scope)
- details about what other headers should be passed along (or not), including content negotiation
- whether to do a "forwarded for" header or not (probably not, for privacy reasons?)
- caching
- websockets
- server-side retries, timeouts, circuit-breaking
- status codes
This references the labels spec, which hasn't merged yet.
=> specs/xrpc: short section on service proxying header

content/guides/applications.md, content/guides/identity.md, content/guides/overview.md
Instead of having these go to `docs.bsky.app`, let's just have them not be links at all for now. I suspect we'll want to do a pass over these "guides" and move/remove/refactor before too long.
Resolves: #307 #294
=> guides: remove all lexicon links

content/specs/lexicon.md
Will probably wait until support lands in atproto (typescript) before merging this.
closes: https://github.com/bluesky-social/atproto-website/issues/171
=> specs: add tid and record-key string formats

content/specs/xrpc.md
Recently merged the change that XRPC proxying is more generic, so can remove the disclaimer from the specs.
=> specs: remove caveat around proxying

content/specs/lexicon.md
In [the `#params` section](https://atproto.com/specs/lexicon#params) of the Lexicon documentation there was a typo where `procedure` was spelled `procedue`. Since this typo is formatted as code, it's probably best to ensure it's correct.
=> Fix a minor typo in the documentation

src/app/[locale]/en.mdx, src/app/[locale]/ja.mdx, src/app/[locale]/pt.mdx
Hello,
I have corrected the link in the image card. It was mistakenly pointing to "https://arxiv.org/abs/2402.03239" instead of the intended "https://steveklabnik.com/writing/how-does-bluesky-work/".
Thank you for reviewing this change.
I would also like to thank you for the recent addition of the Japanese translation on atproto.com!
=> Fix incorrect link in image card

src/app/[locale]/specs/atp/page.mdx, src/app/[locale]/specs/data-model/page.mdx, src/app/[locale]/specs/repository/page.mdx
This strongly de-emphasizes IPLD in the specs. It isn't entirely removed: the data model page now has an explicit section discussion the history and connection between atproto data and IPLD.
The motivation here is two-fold: IPLD can be confusing to devs digging in to atproto for the first time, and there is some potential standards body baggage/history.
In terms of dev understanding: IPLD is conceptually complex, and has a bunch of features/ecosystem we don't use. atproto early adopter devs may have been already familiar with IPLD so the reference was an asset, but now it is probably more confusing. Keeping some reference is helpful in case folks want to re-use IPLD implementation libraries or storage projects.
In terms of standards: we want to pare down our standards "dependency tree" as …
=> specs: remove many references to IPLD

src/app/[locale]/specs/lexicon/page.mdx
Pretty simple, just wasn't explicitly mentioned in the specs.
Closes: https://github.com/bluesky-social/atproto-website/issues/318
=> specs: clarify data encoding of 'token' type

src/app/[locale]/specs/lexicon/page.mdx
tl;dr:
- `union` definition was already good, but word it more strongly, and explicitly say `token` strings are not valid (I had been fuzzy on this)
- `unknown` needs to be an object. It can't be things like a blob, link, or bytes, even though those are "objects" in JSON encoding.
Also recommend against using `unknown` in records, to give us some wiggle room about strict data validation. AKA, we haven't really defined or enforced some of the corner cases around "generic data validation".
Closes: https://github.com/bluesky-social/atproto-website/issues/317
Closes: https://github.com/bluesky-social/atproto-website/issues/319
=> specs: clarify `union` and `unknown` data types

src/app/[locale]/specs/repository/page.mdx
This aligns spec with implementation and data in the network.
I think if we did this over from scratch, could make these "optional" instead to save a tiny bit of data. Maybe can change if we do a v4 iteration? But even then might not be worth the churn.
Thanks @str4d for reporting!
Closes: https://github.com/bluesky-social/atproto-website/issues/312
=> specs/mst: 'left' and 'tree' fields are nullable, not optional

src/app/[locale]/specs/data-model/page.mdx
Closes: https://github.com/bluesky-social/atproto-website/issues/170
I think this covers the basic rule and motivation. We could also mention from Lexicon spec? But this feels like the best spot.
=> specs/data: reserve $-prefixed field names

src/app/[locale]/specs/xrpc/page.mdx
Pulls in the `lxm` and `jti` updates from: https://github.com/bluesky-social/atproto/discussions/2687
And the `iat` and `jti` fields, and `typ` values.
Please review the types (string/number/integer) and whether required or not. I'm not really sure how to specify the data type of, eg, `iat`: it is JSON so can't really say "integer", right? Just numeric? If these are floats, is it expected that they be validated with sub-second precision?
Trying to keep this PR tight/simple, so not reviewing/touching any "should" / "must" type language elsewhere in these sections.
Closes: https://github.com/bluesky-social/atproto-website/issues/327
cc: @rudyfraser doing PDS work and generating inter-service auth JWTs
=> specs/xrpc: more JWT fields; document typ

src/app/[locale]/en.mdx, src/app/[locale]/ja.mdx, src/app/[locale]/pt.mdx
Just fixing a link on the homepage, ensure it points to the lexicon guide rather than the identity guide.
=> Fix link to lexicon guide on homepage

mdx-components.tsx, tsconfig.json
By default a TypeScript program includes all TypeScript files. However, because there’s an `include` pattern, `**/*.mdx`, has to be added for editor support.
The `mdx.checkMdx` option turns subtle error hints in the editor into red squiggly lines.
The global type `MDXProvidedComponents` configures the type of components injected into MDX. This provides support for `<Note />`, `<Image />`, etc.
The `useMDXComponents()` function does not take any arguments. The documentation on which this was based, is wrong.
(https://github.com/vercel/next.js/pull/67188)
For details, see https://github.com/mdx-js/mdx-analyzer
=> Configure MDX editor support

src/app/[locale]/specs/repository/page.mdx
Describes the format and contents of "repo diffs" aka "CAR slices". These are returned by some sync API endpoints, and included in the firehose.
The firehose and sync details will be described in a separate spec document.
=> specs: repository diffs

src/app/[locale]/specs/record-key/page.mdx
Probably shouldn't merge until we get support in to typescript codebase.
This will be used by lexicon resolution.
=> specs: 'nsid' as a record key format

src/app/[locale]/specs/lexicon/page.mdx, src/app/[locale]/specs/record-key/page.mdx, src/app/[locale]/specs/tid/page.mdx, src/components/Navigation.tsx
This is just shuffling / re-organizing, not changing any syntax or semantics.
I did write 1-2 new paragraphs (on the record key page, and the intro paragraph of TID page), but otherwise everything is just copy/pasted around.
If we have proliferated too many specs pages, I'd be in favor of grouping or combining some of these syntax/identifier pages, but for now having them broken out makes it easier to cross-link and look stuff up.
=> specs: break out TID definition from record-key to a separate page

src/app/[locale]/specs/blob/page.mdx
The raw codec is 0x55 rather than 0x00 (see https://github.com/multiformats/multicodec/blob/d08f5064ce50e9e7fabc5bb9a7eeb169ccefebda/table.csv#L41).
Also see https://cid.ipfs.tech/#bafkreibjfgx2gprinfvicegelk5kosd6y2frmqpqzwqkg7usac74l3t2v4
=> fix: raw codec is 0x55

src/app/[locale]/guides/account-lifecycle/en.mdx, src/app/[locale]/guides/account-lifecycle/page.tsx, src/app/[locale]/guides/account-migration/en.mdx, src/app/[locale]/guides/account-migration/page.tsx, src/app/[locale]/specs/account/page.mdx, src/app/[locale]/specs/sync/page.mdx
As discussed, moving these parts of the account+sync specs over from github discussion dumps in to this repo, but as "guides" not directly in the specs. Linked out from "guideline" sections in the specs docs.
Intend to self-merge this after checking that links work.
A possibly confusing aspect is that these are intentionally not linked from the side navigation bar. I don't think they make sense outside the linked context from reading the specs directly; these are basically appendices. We might want, eg, a high-level account migration guide as well in the future, but it would not be written the way the included document is.
=> linked "best practices" guides

src/app/[locale]/guides/glossary/en.mdx
**Fix typo**:  
Update link fragment `#nsid` to `#nsid-namespaced-id`
to fix broken link.
=> Update en.mdx (Fix typo)

src/app/[locale]/specs/xrpc/page.mdx
Because the link is invalid due to the change by #343, the path is updated from `./auth` to `./oauth`.
This is related to another potential issue. #343 adds a redirect, and it [works](https://atproto.com/specs/auth) well on the English page, but the path does not match in other languages, so it [displays](https://atproto.com/ja/specs/auth) 404. More fundamental corrections may be needed, but in any case, we will solve the impending problems.
=> fix link to auth

src/app/[locale]/specs/atp/en.mdx, src/app/[locale]/specs/lexicon/en.mdx
See longer design discussion: https://github.com/bluesky-social/atproto/discussions/3074
Thought about putting some or all of this under the "NSID" specification, but it is really about Lexicons, not just identifiers, so sticking it here.
Note that this also pulls out mention of `revision` in "Lexicon Files" as well. We can always put them back in with same name/type, but I think it is confusing to have that in there with no clear semantics.
=> lexicon resolution spec

src/app/[locale]/specs/nsid/en.mdx
Closes: https://github.com/bluesky-social/atproto-website/issues/391
indigo (golang) PR: https://github.com/bluesky-social/indigo/pull/981
atproto (typescript) PR: https://github.com/bluesky-social/atproto/pull/3633
interop tests PR: https://github.com/bluesky-social/atproto-interop-tests/pull/3
=> NSID: allow digits in 'name' segment

src/components/mdx.tsx, src/mdx/rehype.mjs
I often find myself wanting to link to `h3` headers in documentation (like the various subtypes of events [in the firehose spec](https://atproto.com/specs/sync#firehose)), then realize this is only supported with `h2` headers .
This PR also adds  ids + anchor links to `h3` headers. 
I considered doing this for `h4`s, but that would mean changing the `Heading` component, and I wanted to keep this review as simple as possible. The only `h4`s that currently exist are in the Korean translation, and they have an `h3` header very close (and probably shouldn't be headers at all).
=> Allow direct linking to h3 headers

src/components/LanguageChanger.tsx
Add `aria-label="Language"` to the language changer for a11y purposes, so screen readers will announce the label of the control.
I think there's a potential case to be made for a visual label instead, maybe through an icon like this lucide languages one. But, for sighted users it's fairly obvious that it's a language selector, so it probably is not be needed.
=> fix: Add label to language changer

src/app/[locale]/specs/oauth/en.mdx
Draft because I am still checking that we are compliant with the released RFC.
=> Update link to "Best Current Practice for OAuth 2.0 Security" to RFC9700

src/app/[locale]/specs/handle/en.mdx
re: https://bsky.app/profile/bnewbold.net/post/3lwezl4ztfs2x
the wording can probably be improved (brain is fried), but i think it captures the intent at least.
=> handle: https-well-known method: clients *should* strip some whitespace

src/app/[locale]/guides/applications/en.mdx, src/app/[locale]/guides/applications/ja.mdx, src/app/[locale]/guides/applications/pt.mdx
Use the correct API `agent.com.atproto.repo.putRecord` instead of `agent.com.atproto.putRecord`
=> Fix typo in guides/applications
